name: Terraform Deployment
on: push
jobs:
  test:
    env: 
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: action/checkout@v4
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform Init, Plan
        run: |
          terraform init
          terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
